[env:esp32dev]
platform = espressif32@^6.4.0 ; renovate: datasource=github-tags depName=platformio/platform-espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -Wall
lib_deps =
    knolleary/PubSubClient@^2.8 ; renovate: datasource=github-tags depName=knolleary/pubsubclient
    bblanchon/ArduinoJson@^7.0.4 ; renovate: datasource=github-tags depName=bblanchon/ArduinoJson
    tzapu/WiFiManager@^2.0.17 ; renovate: datasource=github-tags depName=tzapu/WiFiManager
