[env]
platform = espressif32@^6.4.0 ; renovate: datasource=github-tags depName=platformio/platform-espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -Wall
lib_deps =
    knolleary/PubSubClient@^2.8 ; renovate: datasource=github-tags depName=knolleary/pubsubclient
    bblanchon/ArduinoJson@^7.0.4 ; renovate: datasource=github-tags depName=bblanchon/ArduinoJson
    tzapu/WiFiManager@^2.0.17 ; renovate: datasource=github-tags depName=tzapu/WiFiManager

[env:esp32dev]

; Over-the-air upload once the device is built into the bar cabinet.
; Password is the one stored during provisioning.
[env:esp32dev-ota]
upload_protocol = espota
upload_port = bordbar.zimmermann.eu.com
